### ISSUE TITLE
Player list not populating

### ISSUE THREAD

**Issue by spriggangt** [Sepichat/FoundryVTT-GiveItem#37]
Recently Updated to V9 of Foundry and that may have something to do with it, but the player list, when attempting to give an item to a player, is simply not populating, except in one instance, in a different game world, in which is just shows one of my player's companions, a spiritual weapon.  And then on another game world the player list is functioning properly.  Not sure why this is.  I have attempted to refresh, restart foundry and turn off all modules except yours.  Nothing seems to fix the issue.   I was able to get an error code to show here.  All three game world were also imported in the same fashion to The Forge which is the current hosting service I am utilizing.
![image](https://user-images.githubusercontent.com/96674828/147400079-966c1664-1a7a-4dc5-b8c4-6278a8b661a9.png)

**Comment by Sepichat** [comment]
Hey @spriggangt 
I tried to reproduce this issue but I could not...
There plugin was not developed to work with Foundry v9 so it was not working properly.
I just fixed the bugs and will publish a new version in a moment, so could you try to use the latest version and let me know if you still have that issue?
Based on the error you provided it looks like you are trying to send an item to an actor that does not exist (the game cannot find the actor based on the ID provided)
In case the issue persist, I might need some help to configure a world in a way where I can have the same behavior.

**Comment by spriggangt** [comment]
Hey just updated.  Still getting the same issue.  It's almost certainly a world generation issue of some type I think.  In the worlds where I am experiencing this, no modules, all modules the issue persists.  Even though I have multiple actors in the world and on the map.  It so odd that it works on one of my games but not others.  I am happy to provide any information I have.  
Can even get you into a discord to show you if you like.

**Comment by spriggangt** [comment]
Okay I tracked down the culprit.  It's an interaction with DDB importer.  When importing an adventure using it it breaks your module.  Any world where I have not done that it is working.  Tested it in like 5 new worlds for each.  Every time the importer was used it broke things.  Evertime I left the world fresh or used one of the adventures in the bazaar there were no problems.

**Comment by Sepichat** [comment]
Thanks a lot for your investigation @spriggangt .
It might still be worth checking what exactly is the issue and what happens when the module interacts with The Forge (which I do not know at all). If you could please explain/show me how I could reproduce the issue, I could try to find out how to fix it.
